// Generated by nuxt-api-party
import type { ApiClient, OpenAPIClient, ApiClientFetchOptions, OpenAPIClientFetchOptions } from '../../node_modules/nuxt-api-party/dist/runtime/composables/$api'
import type { UseApiData, UseOpenAPIData, UseApiDataOptions, UseOpenAPIDataOptions } from '../../node_modules/nuxt-api-party/dist/runtime/composables/useApiData'



// OpenAPI helpers
export type { FetchResponseData, FetchResponseError, MethodOption, ParamsOption, RequestBodyOption, FilterMethods } from '../../node_modules/nuxt-api-party/dist/runtime/openapi'
// Clients
export type { ApiClient, OpenAPIClient, ApiClientFetchOptions, OpenAPIClientFetchOptions, UseApiData, UseOpenAPIData, UseApiDataOptions, UseOpenAPIDataOptions }

export declare const $pokemon: ApiClient
export declare const usePokemonData: UseApiData
export declare const $rickMorty: ApiClient
export declare const useRickMortyData: UseApiData
